### ISSUE TITLE
jar from source crashes on launch

### ISSUE THREAD

**Issue by fiws** [kyrptonaught/linkedstorage#10]
it looks like the build from the repo here does not include the [wanted resource pack](https://github.com/kyrptonaught/linkedstorage/blob/master/src/main/java/net/kyrptonaught/linkedstorage/LinkedStorageModClient.java#L61)

so it crashes on startup:

<details>
<summary>Logs</summary>

```
---- Minecraft Crash Report ----
// Why did you do that?

Time: 6/22/20, 11:51 PM
Description: Initializing game

java.lang.NullPointerException: in is null
	at java.base/java.util.zip.ZipInputStream.<init>(ZipInputStream.java:103)
	at java.base/java.util.zip.ZipInputStream.<init>(ZipInputStream.java:82)
	at net.kyrptonaught.linkedstorage.client.InputStreamResourcePack.<init>(InputStreamResourcePack.java:32)
	at net.kyrptonaught.linkedstorage.LinkedStorageModClient$1$1.<init>(LinkedStorageModClient.java:61)
	at net.kyrptonaught.linkedstorage.LinkedStorageModClient$1.method_14453(LinkedStorageModClient.java:61)
	at net.minecraft.class_3283.method_14445(class_3283.java:33)
	at net.minecraft.class_315.method_1627(class_315.java:669)
	at net.minecraft.class_310.<init>(class_310.java:440)
	at net.minecraft.client.main.Main.main(Main.java:166)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at java.base/java.util.zip.ZipInputStream.<init>(ZipInputStream.java:103)
	at java.base/java.util.zip.ZipInputStream.<init>(ZipInputStream.java:82)
	at net.kyrptonaught.linkedstorage.client.InputStreamResourcePack.<init>(InputStreamResourcePack.java:32)
	at net.kyrptonaught.linkedstorage.LinkedStorageModClient$1$1.<init>(LinkedStorageModClient.java:61)
	at net.kyrptonaught.linkedstorage.LinkedStorageModClient$1.method_14453(LinkedStorageModClient.java:61)
	at net.minecraft.class_3283.method_14445(class_3283.java:33)
	at net.minecraft.class_315.method_1627(class_315.java:669)
	at net.minecraft.class_310.<init>(class_310.java:440)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:166)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)

-- System Details --
Details:
	Minecraft Version: 1.15.2
	Minecraft Version ID: 1.15.2
	Operating System: Linux (amd64) version 5.7.4-arch1-1
	Java Version: 14.0.1, N/A
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 794189712 bytes (757 MB) / 1509949440 bytes (1440 MB) up to 6274678784 bytes (5984 MB)
	CPUs: 12
	JVM Flags: 8 total; -Xss128M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M -XX:ErrorFile=./jvm-error.log
	Fabric Mods: 
		blue_endless_jankson: jankson +
		cloth-basic-math: Cloth Basic Math 0.4.1
		cloth-config2: Cloth Config v2 2.11.2
		fabric: Fabric API 0.13.1+local-unknown
		fabric-api-base: Fabric API Base 0.1.2+nogit
		fabric-biomes-v1: Fabric Biomes (v1) 0.1.5+nogit
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.4+nogit
		fabric-climbable-api-v1: Fabric Climbable API (v1) 1.0.0+nogit
		fabric-command-api-v1: Fabric Command API (v1) 1.0.2+nogit
		fabric-commands-v0: Fabric Commands (v0) 0.2.0+nogit
		fabric-containers-v0: Fabric Containers (v0) 0.1.3+nogit
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.1.3+nogit
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+nogit
		fabric-dimensions-v1: fabric-dimensions-v1 0.3.0+nogit
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.3.0+nogit
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.1.2+nogit
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.0+nogit
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.0+nogit
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.0+nogit
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 0.1.5+nogit
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.2+nogit
		fabric-models-v0: Fabric Models (v0) 0.1.0+nogit
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.3+nogit
		fabric-networking-v0: Fabric Networking (v0) 0.1.10+nogit
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.2.1+nogit
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.5.1+nogit
		fabric-particles-v1: fabric-particles-v1 0.2.1+nogit
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.2.6+nogit
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.2.10+nogit
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.2.23+nogit
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.0.1+nogit
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.3+nogit
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.6+nogit
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.0+nogit
		fabric-rendering-v1: Fabric Rendering (v1) 1.0.0+nogit
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.1.10+nogit
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 0.1.3+nogit
		fabric-textures-v0: Fabric Textures (v0) 1.0.4+nogit
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.1.0+nogit
		fabricloader: Fabric Loader 0.8.8+build.202
		kyrptconfig: Kytpt Config 1.0.0
		linkedstorage: Linked Storage 1.3.1
		minecraft: Minecraft 1.15.2
		minepkg-companion: minepkg-companion 0.1.0
	Launched Version: 1.15.2
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce GTX 980/PCIe/SSE2 GL version 4.6.0 NVIDIA 440.82, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	CPU: 12x Intel(R) Core(TM) i7-5820K CPU @ 3.30GHz
#@!@# Game crashed! Crash report saved to: #@!@# /tmp/linkedstorage147065883/minecraft/crash-reports/crash-2020-06-22_23.51.14-client.txt
--------------------
Minecraft crashed :(

```

</details>

maybe make it optional or include it here?

**Comment by kyrptonaught** [comment]
Nice catch, the resourcepack has been added to both the 1.15 branch and 1.16
