### ISSUE TITLE
Can't open any containers when on dedicated server

### ISSUE THREAD

**Issue by tom5454** [kyrptonaught/linkedstorage#13]
Version: 1.3.4-1.16
Error executing task on Client:
java.lang.NullPointerException: null
	at net.kyrptonaught.linkedstorage.LinkedStorageMod.getInventory(LinkedStorageMod.java:63)
	at net.kyrptonaught.linkedstorage.inventory.LinkedContainer.<init>(LinkedContainer.java:27)
	at net.fabricmc.fabric.impl.screenhandler.ExtendedScreenHandlerType.create(ExtendedScreenHandlerType.java:44)
	....
LinkedStorageMod.CMAN is null/not initialized when connected to dedicated servers.

**Comment by kyrptonaught** [comment]
fixed in 1.3.5
